code --install-extension alefragnani.project-manager
code --install-extension andys8.jest-snippets
code --install-extension Angelmaneuver.wallpaper-setting
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension ChakrounAnas.turbo-console-log
code --install-extension cipchk.cssrem
code --install-extension codezombiech.gitignore
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension dracula-theme-pro.theme-dracula-pro
code --install-extension e-squad-extension.e-squad-extensions
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension ExodiusStudios.comment-anchors
code --install-extension formulahendry.auto-rename-tag
code --install-extension GitHub.copilot
code --install-extension GitHub.copilot-chat
code --install-extension infeng.vscode-react-typescript
code --install-extension junstyle.php-cs-fixer
code --install-extension MehediDracula.php-namespace-resolver
code --install-extension mhutchie.git-graph
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.symbols
code --install-extension mikestead.dotenv
code --install-extension mohsen1.prettify-json
code --install-extension ms-azuretools.vscode-docker
code --install-extension MS-CEINTL.vscode-language-pack-pt-BR
code --install-extension natqe.reload
code --install-extension naumovs.color-highlight
code --install-extension oderwat.indent-rainbow
code --install-extension omthemes.om-extension-pack
code --install-extension ritwickdey.LiveServer
code --install-extension rvest.vs-code-prettier-eslint
code --install-extension sketchbuch.vsc-workspace-sidebar
code --install-extension stylelint.vscode-stylelint
code --install-extension Tyriar.sort-lines
code --install-extension waderyan.gitblame
code --install-extension WallabyJs.quokka-vscode